language: c
sudo: required
compiler:
  - gcc
before_install:
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get update -q
  - sudo apt-get install libsodium-dev -y
script:
  - make check
notifications:
  email: false
